[project]
name = "multiview-calib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "imageio>=2.37.2",
    "matplotlib>=3.10.8",
    "networkx>=3.6.1",
    "numpy<2",
    "opencv-contrib-python<4.8",
    "opencv-python<4.8",
    "rerun-sdk<0.24",
    "tqdm>=4.67.3",
]
