[project]
name = "multiview-calib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "imageio>=2.37.2",
    "matplotlib>=3.10.8",
    "networkx>=3.6.1",
    "opencv-contrib-python>=4.13.0.92",
    "opencv-python>=4.13.0.92",
    "rerun-sdk>=0.30.0",
    "tqdm>=4.67.3",
]
